In [4]:
import pandas as pd

CONFIRMED_URL = (
    "https://raw.githubusercontent.com/dsfsi/covid19za/master/data/"
    "covid19za_provincial_cumulative_timeline_confirmed.csv"
)
RECOVERIES_URL = (
    "https://raw.githubusercontent.com/dsfsi/covid19za/master/data/"
    "covid19za_provincial_cumulative_timeline_recoveries.csv"
)

print("pandas", pd.__version__)

pandas 3.0.5

In [5]:
confirmed = pd.read_csv(CONFIRMED_URL)
recoveries = pd.read_csv(RECOVERIES_URL)

print("confirmed shape:", confirmed.shape)
print("recoveries shape:", recoveries.shape)
print("confirmed columns:", list(confirmed.columns))
print("recoveries columns:", list(recoveries.columns))

confirmed shape: (864, 14)
recoveries shape: (805, 14)
confirmed columns: ['date', 'YYYYMMDD', 'EC', 'FS', 'GP', 'KZN', 'LP', 'MP', 'NC', 'NW', 'WC', 'UNKNOWN', 'total', 'source']
recoveries columns: ['date', 'YYYYMMDD', 'EC', 'FS', 'GP', 'KZN', 'LP', 'MP', 'NC', 'NW', 'WC', 'UNKNOWN', 'total', 'source']

In [6]:
print("Confirmed — first 3 rows")
display(confirmed.head(3))
print("Confirmed — last 2 rows")
display(confirmed.tail(2))
print("Recoveries — first 2 rows")
display(recoveries.head(2))
print("Recoveries — last 2 rows")
display(recoveries.tail(2))

Confirmed — first 3 rows

,date,YYYYMMDD,EC,FS,GP,KZN,LP,MP,NC,NW,WC,UNKNOWN,total,source
0,05-03-2020,20200305,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,NaN
1,07-03-2020,20200307,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2,NaN
2,08-03-2020,20200308,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3,NaN

Confirmed — last 2 rows

,date,YYYYMMDD,EC,FS,GP,KZN,LP,MP,NC,NW,WC,UNKNOWN,total,source
862,22-07-2022,20220722,364070.0,216016.0,1324602.0,716799.0,159623.0,202125.0,115279.0,201973.0,701646.0,0.0,4002133,https://www.nicd.ac.za/latest-confirmed-cases-...
863,25-07-2022,20220725,364100.0,216038.0,1324948.0,716934.0,159645.0,202162.0,115290.0,201987.0,701877.0,0.0,4002981,sacoronavirus_scrape_gdb

Recoveries — first 2 rows

,date,YYYYMMDD,EC,FS,GP,KZN,LP,MP,NC,NW,WC,UNKNOWN,total,source
0,17-04-2020,20200417,9,71,479,96,18,9,10,6,205,0,903,https://twitter.com/nicd_sa/status/12512151947...
1,18-04-2020,20200418,9,71,479,96,18,9,10,6,205,0,903,https://twitter.com/nicd_sa/status/12515952235...

Recoveries — last 2 rows

,date,YYYYMMDD,EC,FS,GP,KZN,LP,MP,NC,NW,WC,UNKNOWN,total,source
803,22-07-2022,20220722,347030,206976,1302836,699574,154896,197165,111906,196837,676996,0,3894216,sacoronavirus_scrape_gdb
804,25-07-2022,20220725,347035,207054,1303183,699574,154921,197220,111906,196837,677117,0,3894847,sacoronavirus_scrape_gdb

In [7]:
check_date = "01-07-2021"

c = confirmed.loc[confirmed["date"] == check_date, ["date", "YYYYMMDD", "GP", "total"]]
r = recoveries.loc[recoveries["date"] == check_date, ["date", "YYYYMMDD", "GP", "total"]]

print("Confirmed 1 Jul 2021 — expect GP 662300, total 1995556")
display(c)
print("Recoveries 1 Jul 2021 — expect GP 554529, total 1754793")
display(r)

Confirmed 1 Jul 2021 — expect GP 662300, total 1995556

           date  YYYYMMDD        GP    total
481  01-07-2021  20210701  662300.0  1995556

Recoveries 1 Jul 2021 — expect GP 554529, total 1754793

           date  YYYYMMDD      GP    total
434  01-07-2021  20210701  554529  1754793

In [8]:
print("sample confirmed dates:", confirmed["date"].head(3).tolist())
print("sample recoveries dates:", recoveries["date"].head(3).tolist())
print("any ISO dates in confirmed?", confirmed["date"].astype(str).str.match(r"^\d{4}-\d{2}-\d{2}$").any())
print("any ISO dates in recoveries?", recoveries["date"].astype(str).str.match(r"^\d{4}-\d{2}-\d{2}$").any())

sample confirmed dates: ['05-03-2020', '07-03-2020', '08-03-2020']
sample recoveries dates: ['17-04-2020', '18-04-2020', '19-04-2020']
any ISO dates in confirmed? False
any ISO dates in recoveries? False

In [9]:
print("date dtype:", confirmed["date"].dtype)
print("YYYYMMDD dtype:", confirmed["YYYYMMDD"].dtype)
print("first dates:", confirmed["date"].head(3).tolist())

mask_c = confirmed["YYYYMMDD"].astype(str).str.replace(".0", "", regex=False) == "20210701"
mask_r = recoveries["YYYYMMDD"].astype(str).str.replace(".0", "", regex=False) == "20210701"

print("\nConfirmed 1 Jul 2021")
print(confirmed.loc[mask_c, ["date", "YYYYMMDD", "GP", "total"]].to_string(index=False))

print("\nRecoveries 1 Jul 2021")
print(recoveries.loc[mask_r, ["date", "YYYYMMDD", "GP", "total"]].to_string(index=False))

print("\nISO-looking dates in confirmed?", confirmed["date"].astype(str).str.match(r"^\d{4}-\d{2}-\d{2}").any())
print("ISO-looking dates in recoveries?", recoveries["date"].astype(str).str.match(r"^\d{4}-\d{2}-\d{2}").any())

date dtype: str
YYYYMMDD dtype: int64
first dates: ['05-03-2020', '07-03-2020', '08-03-2020']

Confirmed 1 Jul 2021
      date  YYYYMMDD       GP   total
01-07-2021  20210701 662300.0 1995556

Recoveries 1 Jul 2021
      date  YYYYMMDD     GP   total
01-07-2021  20210701 554529 1754793

ISO-looking dates in confirmed? False
ISO-looking dates in recoveries? False

In [11]:
from pathlib import Path
import pandas as pd

landing = Path.home() / "Desktop" / "za-pulse-covid19-analytics" / "data" / "landing"
landing.mkdir(parents=True, exist_ok=True)

province_cols = ["EC", "FS", "GP", "KZN", "LP", "MP", "NC", "NW", "WC", "UNKNOWN", "total"]

def to_landing(df, filename):
    out = df.rename(columns={
        "date": "DateText",
        "YYYYMMDD": "YearMonthDay",
        "UNKNOWN": "UnknownCount",
        "total": "Total",
        "source": "SourceText",
    }).copy()

    for col in ["EC", "FS", "GP", "KZN", "LP", "MP", "NC", "NW", "WC", "UnknownCount", "Total"]:
        out[col] = pd.to_numeric(out[col], errors="coerce").astype("Int64")

    out["YearMonthDay"] = out["YearMonthDay"].astype("Int64").astype(str)
    cols = [
        "DateText", "YearMonthDay",
        "EC", "FS", "GP", "KZN", "LP", "MP", "NC", "NW", "WC",
        "UnknownCount", "Total", "SourceText",
    ]
    path = landing / filename
    out[cols].to_csv(path, index=False)
    print(path)
    print("rows written:", len(out))
    return path

p1 = to_landing(confirmed, "confirmed.csv")
p2 = to_landing(recoveries, "recoveries.csv")

C:\Users\shadr\Desktop\za-pulse-covid19-analytics\data\landing\confirmed.csv
rows written: 864
C:\Users\shadr\Desktop\za-pulse-covid19-analytics\data\landing\recoveries.csv
rows written: 805